all: small crush big
	

small: run_SmallCrush.c
	gcc run_SmallCrush.c -l testu01 -o run_SmallCrush.out

crush: run_Crush.c
	gcc run_Crush.c -l testu01 -o run_Crush.out

big: run_BigCrush.c
	gcc run_BigCrush.c -l testu01 -o run_BigCrush.out
